package openmeteo

type ForecastAPIResponse struct {
	Latitude             float64 `json:"latitude"`
	Longitude            float64 `json:"longitude"`
	GenerationtimeMs     float64 `json:"generationtime_ms"`
	UtcOffsetSeconds     int     `json:"utc_offset_seconds"`
	Timezone             string  `json:"timezone"`
	TimezoneAbbreviation string  `json:"timezone_abbreviation"`
	Elevation            float64 `json:"elevation"`
	HourlyUnits          struct {
		Time                                       string `json:"time"`
		FreezingLevelHeightGemSeamless             string `json:"freezing_level_height_gem_seamless"`
		IsDayGemSeamless                           string `json:"is_day_gem_seamless"`
		Temperature2MGemSeamless                   string `json:"temperature_2m_gem_seamless"`
		WeatherCodeGemSeamless                     string `json:"weather_code_gem_seamless"`
		ApparentTemperatureGemSeamless             string `json:"apparent_temperature_gem_seamless"`
		PrecipitationProbabilityGemSeamless        string `json:"precipitation_probability_gem_seamless"`
		PrecipitationGemSeamless                   string `json:"precipitation_gem_seamless"`
		CloudCoverGemSeamless                      string `json:"cloud_cover_gem_seamless"`
		CloudCoverLowGemSeamless                   string `json:"cloud_cover_low_gem_seamless"`
		CloudCoverMidGemSeamless                   string `json:"cloud_cover_mid_gem_seamless"`
		CloudCoverHighGemSeamless                  string `json:"cloud_cover_high_gem_seamless"`
		VisibilityGemSeamless                      string `json:"visibility_gem_seamless"`
		WindSpeed10MGemSeamless                    string `json:"wind_speed_10m_gem_seamless"`
		WindDirection10MGemSeamless                string `json:"wind_direction_10m_gem_seamless"`
		WindGusts10MGemSeamless                    string `json:"wind_gusts_10m_gem_seamless"`
		RelativeHumidity2MGemSeamless              string `json:"relative_humidity_2m_gem_seamless"`
		RainGemSeamless                            string `json:"rain_gem_seamless"`
		ShowersGemSeamless                         string `json:"showers_gem_seamless"`
		SnowfallGemSeamless                        string `json:"snowfall_gem_seamless"`
		SnowDepthGemSeamless                       string `json:"snow_depth_gem_seamless"`
		FreezingLevelHeightEcmwfIfs                string `json:"freezing_level_height_ecmwf_ifs"`
		IsDayEcmwfIfs                              string `json:"is_day_ecmwf_ifs"`
		Temperature2MEcmwfIfs                      string `json:"temperature_2m_ecmwf_ifs"`
		WeatherCodeEcmwfIfs                        string `json:"weather_code_ecmwf_ifs"`
		ApparentTemperatureEcmwfIfs                string `json:"apparent_temperature_ecmwf_ifs"`
		PrecipitationProbabilityEcmwfIfs           string `json:"precipitation_probability_ecmwf_ifs"`
		PrecipitationEcmwfIfs                      string `json:"precipitation_ecmwf_ifs"`
		CloudCoverEcmwfIfs                         string `json:"cloud_cover_ecmwf_ifs"`
		CloudCoverLowEcmwfIfs                      string `json:"cloud_cover_low_ecmwf_ifs"`
		CloudCoverMidEcmwfIfs                      string `json:"cloud_cover_mid_ecmwf_ifs"`
		CloudCoverHighEcmwfIfs                     string `json:"cloud_cover_high_ecmwf_ifs"`
		VisibilityEcmwfIfs                         string `json:"visibility_ecmwf_ifs"`
		WindSpeed10MEcmwfIfs                       string `json:"wind_speed_10m_ecmwf_ifs"`
		WindDirection10MEcmwfIfs                   string `json:"wind_direction_10m_ecmwf_ifs"`
		WindGusts10MEcmwfIfs                       string `json:"wind_gusts_10m_ecmwf_ifs"`
		RelativeHumidity2MEcmwfIfs                 string `json:"relative_humidity_2m_ecmwf_ifs"`
		RainEcmwfIfs                               string `json:"rain_ecmwf_ifs"`
		ShowersEcmwfIfs                            string `json:"showers_ecmwf_ifs"`
		SnowfallEcmwfIfs                           string `json:"snowfall_ecmwf_ifs"`
		SnowDepthEcmwfIfs                          string `json:"snow_depth_ecmwf_ifs"`
		FreezingLevelHeightGfsSeamless             string `json:"freezing_level_height_gfs_seamless"`
		IsDayGfsSeamless                           string `json:"is_day_gfs_seamless"`
		Temperature2MGfsSeamless                   string `json:"temperature_2m_gfs_seamless"`
		WeatherCodeGfsSeamless                     string `json:"weather_code_gfs_seamless"`
		ApparentTemperatureGfsSeamless             string `json:"apparent_temperature_gfs_seamless"`
		PrecipitationProbabilityGfsSeamless        string `json:"precipitation_probability_gfs_seamless"`
		PrecipitationGfsSeamless                   string `json:"precipitation_gfs_seamless"`
		CloudCoverGfsSeamless                      string `json:"cloud_cover_gfs_seamless"`
		CloudCoverLowGfsSeamless                   string `json:"cloud_cover_low_gfs_seamless"`
		CloudCoverMidGfsSeamless                   string `json:"cloud_cover_mid_gfs_seamless"`
		CloudCoverHighGfsSeamless                  string `json:"cloud_cover_high_gfs_seamless"`
		VisibilityGfsSeamless                      string `json:"visibility_gfs_seamless"`
		WindSpeed10MGfsSeamless                    string `json:"wind_speed_10m_gfs_seamless"`
		WindDirection10MGfsSeamless                string `json:"wind_direction_10m_gfs_seamless"`
		WindGusts10MGfsSeamless                    string `json:"wind_gusts_10m_gfs_seamless"`
		RelativeHumidity2MGfsSeamless              string `json:"relative_humidity_2m_gfs_seamless"`
		RainGfsSeamless                            string `json:"rain_gfs_seamless"`
		ShowersGfsSeamless                         string `json:"showers_gfs_seamless"`
		SnowfallGfsSeamless                        string `json:"snowfall_gfs_seamless"`
		SnowDepthGfsSeamless                       string `json:"snow_depth_gfs_seamless"`
		FreezingLevelHeightNcepNbmConus            string `json:"freezing_level_height_ncep_nbm_conus"`
		IsDayNcepNbmConus                          string `json:"is_day_ncep_nbm_conus"`
		Temperature2MNcepNbmConus                  string `json:"temperature_2m_ncep_nbm_conus"`
		WeatherCodeNcepNbmConus                    string `json:"weather_code_ncep_nbm_conus"`
		ApparentTemperatureNcepNbmConus            string `json:"apparent_temperature_ncep_nbm_conus"`
		PrecipitationProbabilityNcepNbmConus       string `json:"precipitation_probability_ncep_nbm_conus"`
		PrecipitationNcepNbmConus                  string `json:"precipitation_ncep_nbm_conus"`
		CloudCoverNcepNbmConus                     string `json:"cloud_cover_ncep_nbm_conus"`
		CloudCoverLowNcepNbmConus                  string `json:"cloud_cover_low_ncep_nbm_conus"`
		CloudCoverMidNcepNbmConus                  string `json:"cloud_cover_mid_ncep_nbm_conus"`
		CloudCoverHighNcepNbmConus                 string `json:"cloud_cover_high_ncep_nbm_conus"`
		VisibilityNcepNbmConus                     string `json:"visibility_ncep_nbm_conus"`
		WindSpeed10MNcepNbmConus                   string `json:"wind_speed_10m_ncep_nbm_conus"`
		WindDirection10MNcepNbmConus               string `json:"wind_direction_10m_ncep_nbm_conus"`
		WindGusts10MNcepNbmConus                   string `json:"wind_gusts_10m_ncep_nbm_conus"`
		RelativeHumidity2MNcepNbmConus             string `json:"relative_humidity_2m_ncep_nbm_conus"`
		RainNcepNbmConus                           string `json:"rain_ncep_nbm_conus"`
		ShowersNcepNbmConus                        string `json:"showers_ncep_nbm_conus"`
		SnowfallNcepNbmConus                       string `json:"snowfall_ncep_nbm_conus"`
		SnowDepthNcepNbmConus                      string `json:"snow_depth_ncep_nbm_conus"`
		FreezingLevelHeightGfsGraphcast025         string `json:"freezing_level_height_gfs_graphcast025"`
		IsDayGfsGraphcast025                       string `json:"is_day_gfs_graphcast025"`
		Temperature2MGfsGraphcast025               string `json:"temperature_2m_gfs_graphcast025"`
		WeatherCodeGfsGraphcast025                 string `json:"weather_code_gfs_graphcast025"`
		ApparentTemperatureGfsGraphcast025         string `json:"apparent_temperature_gfs_graphcast025"`
		PrecipitationProbabilityGfsGraphcast025    string `json:"precipitation_probability_gfs_graphcast025"`
		PrecipitationGfsGraphcast025               string `json:"precipitation_gfs_graphcast025"`
		CloudCoverGfsGraphcast025                  string `json:"cloud_cover_gfs_graphcast025"`
		CloudCoverLowGfsGraphcast025               string `json:"cloud_cover_low_gfs_graphcast025"`
		CloudCoverMidGfsGraphcast025               string `json:"cloud_cover_mid_gfs_graphcast025"`
		CloudCoverHighGfsGraphcast025              string `json:"cloud_cover_high_gfs_graphcast025"`
		VisibilityGfsGraphcast025                  string `json:"visibility_gfs_graphcast025"`
		WindSpeed10MGfsGraphcast025                string `json:"wind_speed_10m_gfs_graphcast025"`
		WindDirection10MGfsGraphcast025            string `json:"wind_direction_10m_gfs_graphcast025"`
		WindGusts10MGfsGraphcast025                string `json:"wind_gusts_10m_gfs_graphcast025"`
		RelativeHumidity2MGfsGraphcast025          string `json:"relative_humidity_2m_gfs_graphcast025"`
		RainGfsGraphcast025                        string `json:"rain_gfs_graphcast025"`
		ShowersGfsGraphcast025                     string `json:"showers_gfs_graphcast025"`
		SnowfallGfsGraphcast025                    string `json:"snowfall_gfs_graphcast025"`
		SnowDepthGfsGraphcast025                   string `json:"snow_depth_gfs_graphcast025"`
		FreezingLevelHeightEcmwfAifs025Single      string `json:"freezing_level_height_ecmwf_aifs025_single"`
		IsDayEcmwfAifs025Single                    string `json:"is_day_ecmwf_aifs025_single"`
		Temperature2MEcmwfAifs025Single            string `json:"temperature_2m_ecmwf_aifs025_single"`
		WeatherCodeEcmwfAifs025Single              string `json:"weather_code_ecmwf_aifs025_single"`
		ApparentTemperatureEcmwfAifs025Single      string `json:"apparent_temperature_ecmwf_aifs025_single"`
		PrecipitationProbabilityEcmwfAifs025Single string `json:"precipitation_probability_ecmwf_aifs025_single"`
		PrecipitationEcmwfAifs025Single            string `json:"precipitation_ecmwf_aifs025_single"`
		CloudCoverEcmwfAifs025Single               string `json:"cloud_cover_ecmwf_aifs025_single"`
		CloudCoverLowEcmwfAifs025Single            string `json:"cloud_cover_low_ecmwf_aifs025_single"`
		CloudCoverMidEcmwfAifs025Single            string `json:"cloud_cover_mid_ecmwf_aifs025_single"`
		CloudCoverHighEcmwfAifs025Single           string `json:"cloud_cover_high_ecmwf_aifs025_single"`
		VisibilityEcmwfAifs025Single               string `json:"visibility_ecmwf_aifs025_single"`
		WindSpeed10MEcmwfAifs025Single             string `json:"wind_speed_10m_ecmwf_aifs025_single"`
		WindDirection10MEcmwfAifs025Single         string `json:"wind_direction_10m_ecmwf_aifs025_single"`
		WindGusts10MEcmwfAifs025Single             string `json:"wind_gusts_10m_ecmwf_aifs025_single"`
		RelativeHumidity2MEcmwfAifs025Single       string `json:"relative_humidity_2m_ecmwf_aifs025_single"`
		RainEcmwfAifs025Single                     string `json:"rain_ecmwf_aifs025_single"`
		ShowersEcmwfAifs025Single                  string `json:"showers_ecmwf_aifs025_single"`
		SnowfallEcmwfAifs025Single                 string `json:"snowfall_ecmwf_aifs025_single"`
		SnowDepthEcmwfAifs025Single                string `json:"snow_depth_ecmwf_aifs025_single"`
		FreezingLevelHeightNcepNamConus            string `json:"freezing_level_height_ncep_nam_conus"`
		IsDayNcepNamConus                          string `json:"is_day_ncep_nam_conus"`
		Temperature2MNcepNamConus                  string `json:"temperature_2m_ncep_nam_conus"`
		WeatherCodeNcepNamConus                    string `json:"weather_code_ncep_nam_conus"`
		ApparentTemperatureNcepNamConus            string `json:"apparent_temperature_ncep_nam_conus"`
		PrecipitationProbabilityNcepNamConus       string `json:"precipitation_probability_ncep_nam_conus"`
		PrecipitationNcepNamConus                  string `json:"precipitation_ncep_nam_conus"`
		CloudCoverNcepNamConus                     string `json:"cloud_cover_ncep_nam_conus"`
		CloudCoverLowNcepNamConus                  string `json:"cloud_cover_low_ncep_nam_conus"`
		CloudCoverMidNcepNamConus                  string `json:"cloud_cover_mid_ncep_nam_conus"`
		CloudCoverHighNcepNamConus                 string `json:"cloud_cover_high_ncep_nam_conus"`
		VisibilityNcepNamConus                     string `json:"visibility_ncep_nam_conus"`
		WindSpeed10MNcepNamConus                   string `json:"wind_speed_10m_ncep_nam_conus"`
		WindDirection10MNcepNamConus               string `json:"wind_direction_10m_ncep_nam_conus"`
		WindGusts10MNcepNamConus                   string `json:"wind_gusts_10m_ncep_nam_conus"`
		RelativeHumidity2MNcepNamConus             string `json:"relative_humidity_2m_ncep_nam_conus"`
		RainNcepNamConus                           string `json:"rain_ncep_nam_conus"`
		ShowersNcepNamConus                        string `json:"showers_ncep_nam_conus"`
		SnowfallNcepNamConus                       string `json:"snowfall_ncep_nam_conus"`
		SnowDepthNcepNamConus                      string `json:"snow_depth_ncep_nam_conus"`
	} `json:"hourly_units"`
	Hourly struct {
		Time                                       []string      `json:"time"`
		FreezingLevelHeightGemSeamless             []interface{} `json:"freezing_level_height_gem_seamless"`
		IsDayGemSeamless                           []int         `json:"is_day_gem_seamless"`
		Temperature2MGemSeamless                   []float64     `json:"temperature_2m_gem_seamless"`
		WeatherCodeGemSeamless                     []int         `json:"weather_code_gem_seamless"`
		ApparentTemperatureGemSeamless             []float64     `json:"apparent_temperature_gem_seamless"`
		PrecipitationProbabilityGemSeamless        []int         `json:"precipitation_probability_gem_seamless"`
		PrecipitationGemSeamless                   []float64     `json:"precipitation_gem_seamless"`
		CloudCoverGemSeamless                      []int         `json:"cloud_cover_gem_seamless"`
		CloudCoverLowGemSeamless                   []int         `json:"cloud_cover_low_gem_seamless"`
		CloudCoverMidGemSeamless                   []int         `json:"cloud_cover_mid_gem_seamless"`
		CloudCoverHighGemSeamless                  []int         `json:"cloud_cover_high_gem_seamless"`
		VisibilityGemSeamless                      []interface{} `json:"visibility_gem_seamless"`
		WindSpeed10MGemSeamless                    []float64     `json:"wind_speed_10m_gem_seamless"`
		WindDirection10MGemSeamless                []int         `json:"wind_direction_10m_gem_seamless"`
		WindGusts10MGemSeamless                    []float64     `json:"wind_gusts_10m_gem_seamless"`
		RelativeHumidity2MGemSeamless              []int         `json:"relative_humidity_2m_gem_seamless"`
		RainGemSeamless                            []float64     `json:"rain_gem_seamless"`
		ShowersGemSeamless                         []float64     `json:"showers_gem_seamless"`
		SnowfallGemSeamless                        []float64     `json:"snowfall_gem_seamless"`
		SnowDepthGemSeamless                       []float64     `json:"snow_depth_gem_seamless"`
		FreezingLevelHeightEcmwfIfs                []interface{} `json:"freezing_level_height_ecmwf_ifs"`
		IsDayEcmwfIfs                              []int         `json:"is_day_ecmwf_ifs"`
		Temperature2MEcmwfIfs                      []float64     `json:"temperature_2m_ecmwf_ifs"`
		WeatherCodeEcmwfIfs                        []int         `json:"weather_code_ecmwf_ifs"`
		ApparentTemperatureEcmwfIfs                []float64     `json:"apparent_temperature_ecmwf_ifs"`
		PrecipitationProbabilityEcmwfIfs           []int         `json:"precipitation_probability_ecmwf_ifs"`
		PrecipitationEcmwfIfs                      []float64     `json:"precipitation_ecmwf_ifs"`
		CloudCoverEcmwfIfs                         []int         `json:"cloud_cover_ecmwf_ifs"`
		CloudCoverLowEcmwfIfs                      []int         `json:"cloud_cover_low_ecmwf_ifs"`
		CloudCoverMidEcmwfIfs                      []int         `json:"cloud_cover_mid_ecmwf_ifs"`
		CloudCoverHighEcmwfIfs                     []int         `json:"cloud_cover_high_ecmwf_ifs"`
		VisibilityEcmwfIfs                         []float64     `json:"visibility_ecmwf_ifs"`
		WindSpeed10MEcmwfIfs                       []float64     `json:"wind_speed_10m_ecmwf_ifs"`
		WindDirection10MEcmwfIfs                   []int         `json:"wind_direction_10m_ecmwf_ifs"`
		WindGusts10MEcmwfIfs                       []float64     `json:"wind_gusts_10m_ecmwf_ifs"`
		RelativeHumidity2MEcmwfIfs                 []int         `json:"relative_humidity_2m_ecmwf_ifs"`
		RainEcmwfIfs                               []float64     `json:"rain_ecmwf_ifs"`
		ShowersEcmwfIfs                            []float64     `json:"showers_ecmwf_ifs"`
		SnowfallEcmwfIfs                           []float64     `json:"snowfall_ecmwf_ifs"`
		SnowDepthEcmwfIfs                          []float64     `json:"snow_depth_ecmwf_ifs"`
		FreezingLevelHeightGfsSeamless             []float64     `json:"freezing_level_height_gfs_seamless"`
		IsDayGfsSeamless                           []int         `json:"is_day_gfs_seamless"`
		Temperature2MGfsSeamless                   []float64     `json:"temperature_2m_gfs_seamless"`
		WeatherCodeGfsSeamless                     []int         `json:"weather_code_gfs_seamless"`
		ApparentTemperatureGfsSeamless             []float64     `json:"apparent_temperature_gfs_seamless"`
		PrecipitationProbabilityGfsSeamless        []int         `json:"precipitation_probability_gfs_seamless"`
		PrecipitationGfsSeamless                   []float64     `json:"precipitation_gfs_seamless"`
		CloudCoverGfsSeamless                      []int         `json:"cloud_cover_gfs_seamless"`
		CloudCoverLowGfsSeamless                   []int         `json:"cloud_cover_low_gfs_seamless"`
		CloudCoverMidGfsSeamless                   []int         `json:"cloud_cover_mid_gfs_seamless"`
		CloudCoverHighGfsSeamless                  []int         `json:"cloud_cover_high_gfs_seamless"`
		VisibilityGfsSeamless                      []float64     `json:"visibility_gfs_seamless"`
		WindSpeed10MGfsSeamless                    []float64     `json:"wind_speed_10m_gfs_seamless"`
		WindDirection10MGfsSeamless                []int         `json:"wind_direction_10m_gfs_seamless"`
		WindGusts10MGfsSeamless                    []float64     `json:"wind_gusts_10m_gfs_seamless"`
		RelativeHumidity2MGfsSeamless              []int         `json:"relative_humidity_2m_gfs_seamless"`
		RainGfsSeamless                            []float64     `json:"rain_gfs_seamless"`
		ShowersGfsSeamless                         []float64     `json:"showers_gfs_seamless"`
		SnowfallGfsSeamless                        []float64     `json:"snowfall_gfs_seamless"`
		SnowDepthGfsSeamless                       []float64     `json:"snow_depth_gfs_seamless"`
		FreezingLevelHeightNcepNbmConus            []interface{} `json:"freezing_level_height_ncep_nbm_conus"`
		IsDayNcepNbmConus                          []int         `json:"is_day_ncep_nbm_conus"`
		Temperature2MNcepNbmConus                  []float64     `json:"temperature_2m_ncep_nbm_conus"`
		WeatherCodeNcepNbmConus                    []int         `json:"weather_code_ncep_nbm_conus"`
		ApparentTemperatureNcepNbmConus            []float64     `json:"apparent_temperature_ncep_nbm_conus"`
		PrecipitationProbabilityNcepNbmConus       []int         `json:"precipitation_probability_ncep_nbm_conus"`
		PrecipitationNcepNbmConus                  []float64     `json:"precipitation_ncep_nbm_conus"`
		CloudCoverNcepNbmConus                     []int         `json:"cloud_cover_ncep_nbm_conus"`
		CloudCoverLowNcepNbmConus                  []interface{} `json:"cloud_cover_low_ncep_nbm_conus"`
		CloudCoverMidNcepNbmConus                  []interface{} `json:"cloud_cover_mid_ncep_nbm_conus"`
		CloudCoverHighNcepNbmConus                 []interface{} `json:"cloud_cover_high_ncep_nbm_conus"`
		VisibilityNcepNbmConus                     []float64     `json:"visibility_ncep_nbm_conus"`
		WindSpeed10MNcepNbmConus                   []float64     `json:"wind_speed_10m_ncep_nbm_conus"`
		WindDirection10MNcepNbmConus               []int         `json:"wind_direction_10m_ncep_nbm_conus"`
		WindGusts10MNcepNbmConus                   []float64     `json:"wind_gusts_10m_ncep_nbm_conus"`
		RelativeHumidity2MNcepNbmConus             []int         `json:"relative_humidity_2m_ncep_nbm_conus"`
		RainNcepNbmConus                           []float64     `json:"rain_ncep_nbm_conus"`
		ShowersNcepNbmConus                        []float64     `json:"showers_ncep_nbm_conus"`
		SnowfallNcepNbmConus                       []float64     `json:"snowfall_ncep_nbm_conus"`
		SnowDepthNcepNbmConus                      []interface{} `json:"snow_depth_ncep_nbm_conus"`
		FreezingLevelHeightGfsGraphcast025         []interface{} `json:"freezing_level_height_gfs_graphcast025"`
		IsDayGfsGraphcast025                       []int         `json:"is_day_gfs_graphcast025"`
		Temperature2MGfsGraphcast025               []float64     `json:"temperature_2m_gfs_graphcast025"`
		WeatherCodeGfsGraphcast025                 []int         `json:"weather_code_gfs_graphcast025"`
		ApparentTemperatureGfsGraphcast025         []interface{} `json:"apparent_temperature_gfs_graphcast025"`
		PrecipitationProbabilityGfsGraphcast025    []interface{} `json:"precipitation_probability_gfs_graphcast025"`
		PrecipitationGfsGraphcast025               []float64     `json:"precipitation_gfs_graphcast025"`
		CloudCoverGfsGraphcast025                  []int         `json:"cloud_cover_gfs_graphcast025"`
		CloudCoverLowGfsGraphcast025               []int         `json:"cloud_cover_low_gfs_graphcast025"`
		CloudCoverMidGfsGraphcast025               []int         `json:"cloud_cover_mid_gfs_graphcast025"`
		CloudCoverHighGfsGraphcast025              []int         `json:"cloud_cover_high_gfs_graphcast025"`
		VisibilityGfsGraphcast025                  []interface{} `json:"visibility_gfs_graphcast025"`
		WindSpeed10MGfsGraphcast025                []float64     `json:"wind_speed_10m_gfs_graphcast025"`
		WindDirection10MGfsGraphcast025            []int         `json:"wind_direction_10m_gfs_graphcast025"`
		WindGusts10MGfsGraphcast025                []interface{} `json:"wind_gusts_10m_gfs_graphcast025"`
		RelativeHumidity2MGfsGraphcast025          []interface{} `json:"relative_humidity_2m_gfs_graphcast025"`
		RainGfsGraphcast025                        []float64     `json:"rain_gfs_graphcast025"`
		ShowersGfsGraphcast025                     []float64     `json:"showers_gfs_graphcast025"`
		SnowfallGfsGraphcast025                    []float64     `json:"snowfall_gfs_graphcast025"`
		SnowDepthGfsGraphcast025                   []interface{} `json:"snow_depth_gfs_graphcast025"`
		FreezingLevelHeightEcmwfAifs025Single      []interface{} `json:"freezing_level_height_ecmwf_aifs025_single"`
		IsDayEcmwfAifs025Single                    []int         `json:"is_day_ecmwf_aifs025_single"`
		Temperature2MEcmwfAifs025Single            []float64     `json:"temperature_2m_ecmwf_aifs025_single"`
		WeatherCodeEcmwfAifs025Single              []int         `json:"weather_code_ecmwf_aifs025_single"`
		ApparentTemperatureEcmwfAifs025Single      []float64     `json:"apparent_temperature_ecmwf_aifs025_single"`
		PrecipitationProbabilityEcmwfAifs025Single []interface{} `json:"precipitation_probability_ecmwf_aifs025_single"`
		PrecipitationEcmwfAifs025Single            []float64     `json:"precipitation_ecmwf_aifs025_single"`
		CloudCoverEcmwfAifs025Single               []int         `json:"cloud_cover_ecmwf_aifs025_single"`
		CloudCoverLowEcmwfAifs025Single            []int         `json:"cloud_cover_low_ecmwf_aifs025_single"`
		CloudCoverMidEcmwfAifs025Single            []int         `json:"cloud_cover_mid_ecmwf_aifs025_single"`
		CloudCoverHighEcmwfAifs025Single           []int         `json:"cloud_cover_high_ecmwf_aifs025_single"`
		VisibilityEcmwfAifs025Single               []interface{} `json:"visibility_ecmwf_aifs025_single"`
		WindSpeed10MEcmwfAifs025Single             []float64     `json:"wind_speed_10m_ecmwf_aifs025_single"`
		WindDirection10MEcmwfAifs025Single         []int         `json:"wind_direction_10m_ecmwf_aifs025_single"`
		WindGusts10MEcmwfAifs025Single             []interface{} `json:"wind_gusts_10m_ecmwf_aifs025_single"`
		RelativeHumidity2MEcmwfAifs025Single       []int         `json:"relative_humidity_2m_ecmwf_aifs025_single"`
		RainEcmwfAifs025Single                     []float64     `json:"rain_ecmwf_aifs025_single"`
		ShowersEcmwfAifs025Single                  []float64     `json:"showers_ecmwf_aifs025_single"`
		SnowfallEcmwfAifs025Single                 []float64     `json:"snowfall_ecmwf_aifs025_single"`
		SnowDepthEcmwfAifs025Single                []interface{} `json:"snow_depth_ecmwf_aifs025_single"`
		FreezingLevelHeightNcepNamConus            []interface{} `json:"freezing_level_height_ncep_nam_conus"`
		IsDayNcepNamConus                          []int         `json:"is_day_ncep_nam_conus"`
		Temperature2MNcepNamConus                  []float64     `json:"temperature_2m_ncep_nam_conus"`
		WeatherCodeNcepNamConus                    []int         `json:"weather_code_ncep_nam_conus"`
		ApparentTemperatureNcepNamConus            []float64     `json:"apparent_temperature_ncep_nam_conus"`
		PrecipitationProbabilityNcepNamConus       []interface{} `json:"precipitation_probability_ncep_nam_conus"`
		PrecipitationNcepNamConus                  []float64     `json:"precipitation_ncep_nam_conus"`
		CloudCoverNcepNamConus                     []int         `json:"cloud_cover_ncep_nam_conus"`
		CloudCoverLowNcepNamConus                  []int         `json:"cloud_cover_low_ncep_nam_conus"`
		CloudCoverMidNcepNamConus                  []int         `json:"cloud_cover_mid_ncep_nam_conus"`
		CloudCoverHighNcepNamConus                 []int         `json:"cloud_cover_high_ncep_nam_conus"`
		VisibilityNcepNamConus                     []float64     `json:"visibility_ncep_nam_conus"`
		WindSpeed10MNcepNamConus                   []float64     `json:"wind_speed_10m_ncep_nam_conus"`
		WindDirection10MNcepNamConus               []int         `json:"wind_direction_10m_ncep_nam_conus"`
		WindGusts10MNcepNamConus                   []float64     `json:"wind_gusts_10m_ncep_nam_conus"`
		RelativeHumidity2MNcepNamConus             []int         `json:"relative_humidity_2m_ncep_nam_conus"`
		RainNcepNamConus                           []float64     `json:"rain_ncep_nam_conus"`
		ShowersNcepNamConus                        []float64     `json:"showers_ncep_nam_conus"`
		SnowfallNcepNamConus                       []float64     `json:"snowfall_ncep_nam_conus"`
		SnowDepthNcepNamConus                      []float64     `json:"snow_depth_ncep_nam_conus"`
	} `json:"hourly"`
	DailyUnits struct {
		Time                                         string `json:"time"`
		SnowfallWaterEquivalentSumGemSeamless        string `json:"snowfall_water_equivalent_sum_gem_seamless"`
		WeatherCodeGemSeamless                       string `json:"weather_code_gem_seamless"`
		SunriseGemSeamless                           string `json:"sunrise_gem_seamless"`
		SunsetGemSeamless                            string `json:"sunset_gem_seamless"`
		WindDirection10MDominantGemSeamless          string `json:"wind_direction_10m_dominant_gem_seamless"`
		SnowfallWaterEquivalentSumEcmwfIfs           string `json:"snowfall_water_equivalent_sum_ecmwf_ifs"`
		WeatherCodeEcmwfIfs                          string `json:"weather_code_ecmwf_ifs"`
		SunriseEcmwfIfs                              string `json:"sunrise_ecmwf_ifs"`
		SunsetEcmwfIfs                               string `json:"sunset_ecmwf_ifs"`
		WindDirection10MDominantEcmwfIfs             string `json:"wind_direction_10m_dominant_ecmwf_ifs"`
		SnowfallWaterEquivalentSumGfsSeamless        string `json:"snowfall_water_equivalent_sum_gfs_seamless"`
		WeatherCodeGfsSeamless                       string `json:"weather_code_gfs_seamless"`
		SunriseGfsSeamless                           string `json:"sunrise_gfs_seamless"`
		SunsetGfsSeamless                            string `json:"sunset_gfs_seamless"`
		WindDirection10MDominantGfsSeamless          string `json:"wind_direction_10m_dominant_gfs_seamless"`
		SnowfallWaterEquivalentSumNcepNbmConus       string `json:"snowfall_water_equivalent_sum_ncep_nbm_conus"`
		WeatherCodeNcepNbmConus                      string `json:"weather_code_ncep_nbm_conus"`
		SunriseNcepNbmConus                          string `json:"sunrise_ncep_nbm_conus"`
		SunsetNcepNbmConus                           string `json:"sunset_ncep_nbm_conus"`
		WindDirection10MDominantNcepNbmConus         string `json:"wind_direction_10m_dominant_ncep_nbm_conus"`
		SnowfallWaterEquivalentSumGfsGraphcast025    string `json:"snowfall_water_equivalent_sum_gfs_graphcast025"`
		WeatherCodeGfsGraphcast025                   string `json:"weather_code_gfs_graphcast025"`
		SunriseGfsGraphcast025                       string `json:"sunrise_gfs_graphcast025"`
		SunsetGfsGraphcast025                        string `json:"sunset_gfs_graphcast025"`
		WindDirection10MDominantGfsGraphcast025      string `json:"wind_direction_10m_dominant_gfs_graphcast025"`
		SnowfallWaterEquivalentSumEcmwfAifs025Single string `json:"snowfall_water_equivalent_sum_ecmwf_aifs025_single"`
		WeatherCodeEcmwfAifs025Single                string `json:"weather_code_ecmwf_aifs025_single"`
		SunriseEcmwfAifs025Single                    string `json:"sunrise_ecmwf_aifs025_single"`
		SunsetEcmwfAifs025Single                     string `json:"sunset_ecmwf_aifs025_single"`
		WindDirection10MDominantEcmwfAifs025Single   string `json:"wind_direction_10m_dominant_ecmwf_aifs025_single"`
		SnowfallWaterEquivalentSumNcepNamConus       string `json:"snowfall_water_equivalent_sum_ncep_nam_conus"`
		WeatherCodeNcepNamConus                      string `json:"weather_code_ncep_nam_conus"`
		SunriseNcepNamConus                          string `json:"sunrise_ncep_nam_conus"`
		SunsetNcepNamConus                           string `json:"sunset_ncep_nam_conus"`
		WindDirection10MDominantNcepNamConus         string `json:"wind_direction_10m_dominant_ncep_nam_conus"`
	} `json:"daily_units"`
	Daily struct {
		Time                                         []string      `json:"time"`
		SnowfallWaterEquivalentSumGemSeamless        []float64     `json:"snowfall_water_equivalent_sum_gem_seamless"`
		WeatherCodeGemSeamless                       []int         `json:"weather_code_gem_seamless"`
		SunriseGemSeamless                           []string      `json:"sunrise_gem_seamless"`
		SunsetGemSeamless                            []string      `json:"sunset_gem_seamless"`
		WindDirection10MDominantGemSeamless          []int         `json:"wind_direction_10m_dominant_gem_seamless"`
		SnowfallWaterEquivalentSumEcmwfIfs           []float64     `json:"snowfall_water_equivalent_sum_ecmwf_ifs"`
		WeatherCodeEcmwfIfs                          []int         `json:"weather_code_ecmwf_ifs"`
		SunriseEcmwfIfs                              []string      `json:"sunrise_ecmwf_ifs"`
		SunsetEcmwfIfs                               []string      `json:"sunset_ecmwf_ifs"`
		WindDirection10MDominantEcmwfIfs             []int         `json:"wind_direction_10m_dominant_ecmwf_ifs"`
		SnowfallWaterEquivalentSumGfsSeamless        []float64     `json:"snowfall_water_equivalent_sum_gfs_seamless"`
		WeatherCodeGfsSeamless                       []int         `json:"weather_code_gfs_seamless"`
		SunriseGfsSeamless                           []string      `json:"sunrise_gfs_seamless"`
		SunsetGfsSeamless                            []string      `json:"sunset_gfs_seamless"`
		WindDirection10MDominantGfsSeamless          []int         `json:"wind_direction_10m_dominant_gfs_seamless"`
		SnowfallWaterEquivalentSumNcepNbmConus       []float64     `json:"snowfall_water_equivalent_sum_ncep_nbm_conus"`
		WeatherCodeNcepNbmConus                      []int         `json:"weather_code_ncep_nbm_conus"`
		SunriseNcepNbmConus                          []string      `json:"sunrise_ncep_nbm_conus"`
		SunsetNcepNbmConus                           []string      `json:"sunset_ncep_nbm_conus"`
		WindDirection10MDominantNcepNbmConus         []int         `json:"wind_direction_10m_dominant_ncep_nbm_conus"`
		SnowfallWaterEquivalentSumGfsGraphcast025    []interface{} `json:"snowfall_water_equivalent_sum_gfs_graphcast025"`
		WeatherCodeGfsGraphcast025                   []int         `json:"weather_code_gfs_graphcast025"`
		SunriseGfsGraphcast025                       []string      `json:"sunrise_gfs_graphcast025"`
		SunsetGfsGraphcast025                        []string      `json:"sunset_gfs_graphcast025"`
		WindDirection10MDominantGfsGraphcast025      []int         `json:"wind_direction_10m_dominant_gfs_graphcast025"`
		SnowfallWaterEquivalentSumEcmwfAifs025Single []float64     `json:"snowfall_water_equivalent_sum_ecmwf_aifs025_single"`
		WeatherCodeEcmwfAifs025Single                []int         `json:"weather_code_ecmwf_aifs025_single"`
		SunriseEcmwfAifs025Single                    []string      `json:"sunrise_ecmwf_aifs025_single"`
		SunsetEcmwfAifs025Single                     []string      `json:"sunset_ecmwf_aifs025_single"`
		WindDirection10MDominantEcmwfAifs025Single   []int         `json:"wind_direction_10m_dominant_ecmwf_aifs025_single"`
		SnowfallWaterEquivalentSumNcepNamConus       []float64     `json:"snowfall_water_equivalent_sum_ncep_nam_conus"`
		WeatherCodeNcepNamConus                      []int         `json:"weather_code_ncep_nam_conus"`
		SunriseNcepNamConus                          []string      `json:"sunrise_ncep_nam_conus"`
		SunsetNcepNamConus                           []string      `json:"sunset_ncep_nam_conus"`
		WindDirection10MDominantNcepNamConus         []int         `json:"wind_direction_10m_dominant_ncep_nam_conus"`
	} `json:"daily"`
}
