// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/location/forecast-point": {
            "get": {
                "description": "Retrieve comprehensive location data including coordinates, elevation, and location metadata for a given latitude and longitude",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get forecast point data",
                "parameters": [
                    {
                        "maximum": 90,
                        "minimum": -90,
                        "type": "number",
                        "example": 39.11539,
                        "description": "Latitude in decimal degrees",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 180,
                        "minimum": -180,
                        "type": "number",
                        "example": -107.6584,
                        "description": "Longitude in decimal degrees",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ForecastPoint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PingResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Response message",
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "types.Coords": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 40.7128
                },
                "longitude": {
                    "type": "number",
                    "example": -74.006
                }
            }
        },
        "types.Elevation": {
            "type": "object",
            "properties": {
                "feet": {
                    "type": "number",
                    "example": 5280
                },
                "meters": {
                    "type": "number",
                    "example": 1609.34
                }
            }
        },
        "types.ForecastPoint": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "$ref": "#/definitions/types.Coords"
                },
                "elevation": {
                    "$ref": "#/definitions/types.Elevation"
                },
                "location": {
                    "$ref": "#/definitions/types.LocationInfo"
                }
            }
        },
        "types.LocationInfo": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "example": "United States"
                },
                "country_code": {
                    "type": "string",
                    "example": "US"
                },
                "county": {
                    "type": "string",
                    "example": "Denver County"
                },
                "name": {
                    "type": "string",
                    "example": "Denver"
                },
                "state": {
                    "type": "string",
                    "example": "Colorado"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Medi-Snow API",
	Description:      "Weather and avalanche forecasting API for ski areas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
